apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  db-name: {{ .Values.postgresql.database | b64enc }}
  db-user: {{ .Values.postgresql.user | b64enc }}
  db-password: {{ .Values.postgresql.password | b64enc }}
  db-port: {{ .Values.postgresql.port | b64enc }}