apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  db-user: {{ .Values.image.environment.user | b64enc }}
  db-name: {{ .Values.image.environment.database | b64enc }}
  db-password: {{ .Values.image.environment.password | b64enc }}
  db-port: {{ .Values.image.environment.port | b64enc }}