# Default values for database.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "alpine"
  port: 5432

postgresql: 
  database: postgres
  user: postgres
  password: password
  port: "5432"

service:
  type: ClusterIP
  port: 80

